name: "Build and Deploy"
on:
  ## Events from external actor, or from code pushed (includes tags pushed)
  push:
    branches:
      - main
      - 'refs/tags/*'
    tags:
      - '*'

  pull_request:
  ## Events from the GitHub UI (as when publishing a release)
  # When a release is "released" (draft or released published, no pre-release) - https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#release
  release:
    types: [released]
  # When a tag or branch is created in the GitHub UI
  create:
jobs:
  build:
    # In the future it would be good to run the tests on amd64 and arm64
    # This will require one of these:
    # https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/
    # https://github.com/marketplace/actions/arm-runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run: |
          make build
      - name: Install dependencies for Tests
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends bats
      - name: Test
        run: make test
      - name: Generate README
        run: make README
      #### Deployment Zone: only on main branch (or tags)
      - name: Login to Docker Hub for Deployment
        if: startsWith('refs/tag', github.ref) || startsWith('refs/heads/main', github.ref)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Deploy
        if: startsWith('refs/tag', github.ref) || startsWith('refs/heads/main', github.ref)
        run: |
          export IMAGE_VERSION="$(echo ${GITHUB_REF#refs/tags/} | grep -v 'refs/heads')"
          export IMAGE_NAME="asciidoctor/docker-asciidoctor"
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          make deploy-README deploy
